alias gsm='git status --untracked-files=no --ignore-submodules'
alias gds='git diff --stat'
alias gdp='git diff HEAD~1 --'
alias gdps='git diff --stat HEAD~1 --'
alias gls='git ls-files -t'
alias l='ls $LS_OPTIONS'
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias la='ls $LS_OPTIONS -lA'
alias lrt='ls -lrt'
alias lh='ls -lhS'
alias mlp='m `ls -rt /tmp/*pdf|tail -1`'
alias rm='rm -i'
alias Rm='command rm -f'
alias cp='cp -i'
alias mv='mv -i'
alias acs='apt-cache search'
alias acss='apt-cache show'
alias agu='sudo apt-get update'
alias agi='sudo apt-get install'
alias bye='exit'
alias y='echo Oops\!'
alias ig='grep -i'
alias f1="awk '{print \$1}'"
alias f2="awk '{print \$2}'"
alias f3="awk '{print \$3}'"
alias f4="awk '{print \$4}'"
alias f5="awk '{print \$5}'"
alias f6="awk '{print \$6}'"
alias f7="awk '{print \$7}'"
alias f8="awk '{print \$8}'"
alias f9="awk '{print \$9}'"
alias f10="awk '{print \$10}'"
alias f11="awk '{print \$11}'"
alias f12="awk '{print \$12}'"
alias f13="awk '{print \$13}'"
alias dm=docker-machine
alias dk=docker-compose
