#!/bin/bash

# link each dotfiles/xxx to ~/.xxx, making backup if needed

backupdir=~/.dotfile-backup
cd `dirname $0`
dotfiles=`pwd`
fmt='%-10s: %s\n'

test -d $backupdir || mkdir $backupdir

for i in .??*; do
    if [ -L ~/$i ]; then
	printf "$fmt" untouched $i 
    elif [[ $i == *.ignore ]]; then
	printf "$fmt" ignored $i 
    else
	test -e ~/$i && mv -i ~/$i $backupdir
	ln -s $dotfiles/$i ~/$i
	printf "$fmt" LINKED $i 
    fi				
done
