#!/bin/bash

# link each dotfiles/xxx to ~/.xxx, making backup if needed

backupdir=~/.dotfile-backup
cd `dirname $0`
dotfiles=`pwd`

test -d $backupdir || mkdir $backupdir

for i in .??*; do
    if [ -L ~/$i ]; then
	echo $i untouched
    elif [[ $i == *.ignore ]]; then
	echo $i ignored
    else
	test -e ~/$i && mv -i ~/$i $backupdir
	ln -s $dotfiles/$i ~/$i
	echo $i linked
    fi				
done
